### ISSUE TITLE
Variable Types - Line 13

### ISSUE THREAD

**Issue by jasonlones** [notallthere2day/save-randomisation-date#3]
Declaring variable types in line 13 is causing crash.  Recommend removing type declarations.

> [This message was automatically generated by REDCap]
> 
> The 'hook_save_record' hook did not complete for the 'save_randomisation_date' module because of the following error:
> 
> Error Message: Uncaught TypeError: Argument 5 passed to NorwichCTU\save_randomization_date\save_randomization_date::redcap_save_record() must be of the type integer, null given in /var/www/html/redcap/modules/save_randomisation_date_v1.0/save_randomization_date.php:13
> Stack trace:
> #0 [internal function]: NorwichCTU\save_randomization_date\save_randomization_date->redcap_save_record(248, '1', 'randomization_f...', 597, NULL, NULL, NULL, 1)
> #1 /var/www/html/redcap/redcap_v9.1.9/ExternalModules/classes/ExternalModules.php(1421): call_user_func_array(Array, Array)
> #2 /var/www/html/redcap/redcap_v9.1.9/ExternalModules/classes/ExternalModules.php(1514): ExternalModules\ExternalModules::startHook('save_randomisat...', 'v1.0', Array)
> #3 /var/www/html/redcap/redcap_v9.1.9/ExternalModules/classes/ExternalModules.php(1529): ExternalModules\ExternalModules::ExternalModules\{closure}('save_randomisat...', 'v1.0')
> #4 /var/www/html/redcap/redcap_v9.1.9/Classes/Hooks.php(41): ExternalModules\ExternalModules::callHook('save_record', Array)
> 
> File: /var/www/html/redcap/modules/save_randomisation_date_v1.0/save_randomization_date.php
> Line: 13

**Comment by notallthere2day** [comment]
this should be fixed in v1.1, but do let me know if you are still having issues.
