### ISSUE TITLE
Request: DATETIME

### ISSUE THREAD

**Issue by jasonlones** [notallthere2day/save-randomisation-date#4]
Quick request, it would be great if the module could return a full datetime (YMDHMS) value.  Many groups want specific times during the day when randomization occurs.

Example, change line 29 to:

$sql = "SELECT DATE_FORMAT(ts, '%Y-%m-%d %h:%i:%s') AS 'logged_date'

**Comment by notallthere2day** [comment]
Thanks Jason- v 1.1 now has this option.
