### ISSUE TITLE
Struggling to get this to save

### ISSUE THREAD

**Issue by npw1982** [notallthere2day/save-randomisation-date#5]
Hi, this is a great idea for an external module, seems surprising that REDCap haven't added this as a bit of standard functionality already :)

Having a bit of trouble getting it to save the actual date though? Does it need to be on the same instrument/separate instrument?

Have tried: 

- All the differing date types for the field/external module
- user role with and without logging permissions.
- instrument that randomise button is on, plus preceding and following instrument at the same event, 

None of these combinations seems to fetch and save the rand date?

Thanks,
Neil

**Comment by notallthere2day** [comment]
Thanks! Yes, I need to release an update for this to make it compatible with newer version of REDCap, where the event log is now split between several tables. Will try and get that out ASAP. Thanks for flagging this up!

**Comment by notallthere2day** [comment]
OK, I've just released version 1.2 which should fix this problem, and submitted it to the EM repository.

**Comment by npw1982** [comment]
Amazing thanks. Will take a look.
